spring:
  datasource:
    hikari:
      driverClassName: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://127.0.0.1:5432/tarkovdb?PrepareThreshold=0
      username: superuser
      password: qwe123_
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: master-pool
    pool:
      initial-size: 5
      min-idle: 5
      max-idle: 10
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
      hibernate.ddl-auto: none
      hibernate.show_slq: true
      hibernate.use_sql_comments: true
#      hibernate.physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB

profileImage:
  type: 'jpg'
  wight: 120
  height: 120

bot:
  name: tarkov_help_bot
  token: 6085174070:AAEibKClfbzfZ35gHnwffapIsphJuRKv65E
  owner: 1074424361

upload:
  directory: C:/Users/Public/Pictures