spring:
  datasource:
    hikari:
      driverClassName: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://127.0.0.1:5432/tarkovdb?PrepareThreshold=0
      username: superuser
      password: qwe123_
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: master-pool
    pool:
      initial-size: 5
      min-idle: 5
      max-idle: 10
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
      hibernate.show_slq: true
      hibernate.use_sql_comments: true
      hibernate.physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl